/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BillsRouteImport } from './routes/bills'
import { Route as CommitteesRouteImport } from './routes/committees'
import { Route as CouncilSessionsRouteImport } from './routes/council-sessions'
import { Route as FactionsRouteImport } from './routes/factions'
import { Route as InterviewConfigsRouteImport } from './routes/interview-configs'
import { Route as ReviewQueueRouteImport } from './routes/review-queue'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as BillContentsBillIdRouteImport } from './routes/bill-contents.$billId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsRoute = BillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitteesRoute = CommitteesRouteImport.update({
  id: '/committees',
  path: '/committees',
  getParentRoute: () => rootRouteImport,
} as any)
const CouncilSessionsRoute = CouncilSessionsRouteImport.update({
  id: '/council-sessions',
  path: '/council-sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const FactionsRoute = FactionsRouteImport.update({
  id: '/factions',
  path: '/factions',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewConfigsRoute = InterviewConfigsRouteImport.update({
  id: '/interview-configs',
  path: '/interview-configs',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewQueueRoute = ReviewQueueRouteImport.update({
  id: '/review-queue',
  path: '/review-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const BillContentsBillIdRoute = BillContentsBillIdRouteImport.update({
  id: '/bill-contents/$billId',
  path: '/bill-contents/$billId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bills': typeof BillsRoute
  '/committees': typeof CommitteesRoute
  '/council-sessions': typeof CouncilSessionsRoute
  '/factions': typeof FactionsRoute
  '/interview-configs': typeof InterviewConfigsRoute
  '/review-queue': typeof ReviewQueueRoute
  '/tags': typeof TagsRoute
  '/bill-contents/$billId': typeof BillContentsBillIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bills': typeof BillsRoute
  '/committees': typeof CommitteesRoute
  '/council-sessions': typeof CouncilSessionsRoute
  '/factions': typeof FactionsRoute
  '/interview-configs': typeof InterviewConfigsRoute
  '/review-queue': typeof ReviewQueueRoute
  '/tags': typeof TagsRoute
  '/bill-contents/$billId': typeof BillContentsBillIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bills': typeof BillsRoute
  '/committees': typeof CommitteesRoute
  '/council-sessions': typeof CouncilSessionsRoute
  '/factions': typeof FactionsRoute
  '/interview-configs': typeof InterviewConfigsRoute
  '/review-queue': typeof ReviewQueueRoute
  '/tags': typeof TagsRoute
  '/bill-contents/$billId': typeof BillContentsBillIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bills'
    | '/committees'
    | '/council-sessions'
    | '/factions'
    | '/interview-configs'
    | '/review-queue'
    | '/tags'
    | '/bill-contents/$billId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bills'
    | '/committees'
    | '/council-sessions'
    | '/factions'
    | '/interview-configs'
    | '/review-queue'
    | '/tags'
    | '/bill-contents/$billId'
  id:
    | '__root__'
    | '/'
    | '/bills'
    | '/committees'
    | '/council-sessions'
    | '/factions'
    | '/interview-configs'
    | '/review-queue'
    | '/tags'
    | '/bill-contents/$billId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillsRoute: typeof BillsRoute
  CommitteesRoute: typeof CommitteesRoute
  CouncilSessionsRoute: typeof CouncilSessionsRoute
  FactionsRoute: typeof FactionsRoute
  InterviewConfigsRoute: typeof InterviewConfigsRoute
  ReviewQueueRoute: typeof ReviewQueueRoute
  TagsRoute: typeof TagsRoute
  BillContentsBillIdRoute: typeof BillContentsBillIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills': {
      id: '/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof BillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/committees': {
      id: '/committees'
      path: '/committees'
      fullPath: '/committees'
      preLoaderRoute: typeof CommitteesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/council-sessions': {
      id: '/council-sessions'
      path: '/council-sessions'
      fullPath: '/council-sessions'
      preLoaderRoute: typeof CouncilSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factions': {
      id: '/factions'
      path: '/factions'
      fullPath: '/factions'
      preLoaderRoute: typeof FactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview-configs': {
      id: '/interview-configs'
      path: '/interview-configs'
      fullPath: '/interview-configs'
      preLoaderRoute: typeof InterviewConfigsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review-queue': {
      id: '/review-queue'
      path: '/review-queue'
      fullPath: '/review-queue'
      preLoaderRoute: typeof ReviewQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bill-contents/$billId': {
      id: '/bill-contents/$billId'
      path: '/bill-contents/$billId'
      fullPath: '/bill-contents/$billId'
      preLoaderRoute: typeof BillContentsBillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillsRoute: BillsRoute,
  CommitteesRoute: CommitteesRoute,
  CouncilSessionsRoute: CouncilSessionsRoute,
  FactionsRoute: FactionsRoute,
  InterviewConfigsRoute: InterviewConfigsRoute,
  ReviewQueueRoute: ReviewQueueRoute,
  TagsRoute: TagsRoute,
  BillContentsBillIdRoute: BillContentsBillIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
